import { revalidatePath } from 'next/cache';
import { z } from 'zod';
import { validatePublication } from '@/features/admin/publish-viewpoint';
import { authorizeAdminRequest } from '@/features/auth/guards';
import { prisma } from '@/lib/db';
import { isSameOrigin, jsonError } from '@/lib/http';
const schema = z.object({ body: z.string(), worryId: z.string(), travelerId: z.string(), authorizationConfirmedAt: z.string().datetime(), authorizationNote: z.string(), idempotencyKey: z.string() });
export async function POST(request: Request) { if (!isSameOrigin(request)) return jsonError('请求来源无效', 403); if (!await authorizeAdminRequest(request)) return jsonError('请先登录', 401); const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return jsonError('观点资料不完整', 400); let data; try { data = validatePublication({ ...parsed.data, authorizationConfirmedAt: new Date(parsed.data.authorizationConfirmedAt) }); } catch { return jsonError('发布前必须确认最终文字、旅人、烦恼与公开授权', 400); } const existing = await prisma.viewpoint.findUnique({ where: { idempotencyKey: data.idempotencyKey } }); const viewpoint = existing ?? await prisma.viewpoint.create({ data }); const worry = await prisma.worry.findUniqueOrThrow({ where: { id: viewpoint.worryId }, select: { slug: true } }); const traveler = await prisma.traveler.findUniqueOrThrow({ where: { id: viewpoint.travelerId }, select: { publicId: true } }); for (const path of ['/', '/town', `/worries/${worry.slug}`, `/travelers/${traveler.publicId}`, '/admin/viewpoints']) revalidatePath(path); return Response.json(viewpoint, { status: existing ? 200 : 201 }); }
export async function PATCH(request: Request) { if (!isSameOrigin(request)) return jsonError('请求来源无效', 403); if (!await authorizeAdminRequest(request)) return jsonError('请先登录', 401); const parsed = z.object({ id: z.string(), status: z.enum(['published', 'hidden', 'deleted']) }).safeParse(await request.json().catch(() => null)); if (!parsed.success) return jsonError('状态数据无效', 400); const viewpoint = await prisma.viewpoint.update({ where: { id: parsed.data.id }, data: { status: parsed.data.status }, include: { worry: true, traveler: true } }); revalidatePath(`/worries/${viewpoint.worry.slug}`); revalidatePath(`/travelers/${viewpoint.traveler.publicId}`); revalidatePath('/town'); return Response.json(viewpoint); }
